### ISSUE TITLE
It is bug or my problem desktop?

### ISSUE THREAD

**Issue by Rodscaloppe** [sereneblue/gnome-shell-extension-colosseum#1]
Gtk.BuilderError: /home/rod/.local/share/gnome-shell/extensions/colosseum@sereneblue/ui/prefs.ui:17:1 Invalid object type 'GtkStackPage'

Stack trace:
  _init@/home/rod/.local/share/gnome-shell/extensions/colosseum@sereneblue/prefs.js:28:21
  buildPrefsWidget@/home/rod/.local/share/gnome-shell/extensions/colosseum@sereneblue/prefs.js:211:13
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:5
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  
It is bug or my problem desktop?

**Comment by sereneblue** [comment]
Hi @Rodscaloppe,

Are you using GNOME 40?

**Comment by Rodscaloppe** [comment]
No, is 3.36.8

**Comment by sereneblue** [comment]
> No, is 3.36.8

This extension only supports GNOME 40.
