### ISSUE TITLE
Premier League update for 23/24 season

### ISSUE THREAD

**Issue by catbabylon** [sereneblue/gnome-shell-extension-colosseum#10]
Hi Serenblue, 

Just an update  on the Premier League teams for 23/24 season which starts next week. Alas, Leeds were relegated last season so this extension is less useful for me now (unless you were to add the EFL Championship ;) )

Arsenal
Aston Villa
Bournemouth
Brentford
Brighton & Hove Albion
Burnley
Chelsea
Crystal Palace
Everton
Fulham 	
Liverpool
Luton Town
Manchester City
Manchester United
Newcastle United 
Nottingham Forest
Sheffield United
Tottenham Hotspur
West Ham United
Wolverhampton Wanderers

**Comment by sereneblue** [comment]
Thanks, I've updated the EPL teams and also added the EFL championship.
