### ISSUE TITLE
EFL Championship listed as a tournament rather than a league

### ISSUE THREAD

**Issue by catbabylon** [sereneblue/gnome-shell-extension-colosseum#11]
Hi Serenblue

Thanks for adding the EFL championship, one slight problem is that it should be included in the leagues section not the tournament section (it is the 2nd tier of English football and runs in the same league system as the EPL). Although I can see the Championship games, I can't pick the teams I want to follow.

thanks again!

**Comment by sereneblue** [comment]
Hi @catbabylon,

Thanks for mentioning this. You'll be able to follow a specific team in the next update.
