### ISSUE TITLE
Enhancement Request: Add NCAAF and NCAAB leagues

### ISSUE THREAD

**Issue by chipsharpdotcom** [sereneblue/gnome-shell-extension-colosseum#12]
I love your extension! I would like to humbly request adding NCAAF and NCAAB leagues to the extension. I see that you're using ESPN's API to pull the info, and I took a swipe at trying to add it myself, but I was quickly reminded that I'm a terrible coder. 

Thank you in advance for your consideration.

**Comment by sereneblue** [comment]
Hi @chipsharpdotcom,

I've added NCAA Football, NCAA Men's Basketball  and NCAA Women's Basketball. They'll be available in the next update.
