### ISSUE TITLE
UEFA Champions League out of date

### ISSUE THREAD

**Issue by MLKahnt** [sereneblue/gnome-shell-extension-colosseum#13]
With the teams playing in the 23/24 group stage now determined, could the available UCL teams be updated to reflect that?

On a related note, would it be possible to also include UEFA Europa League, UEFA Europa Conference League, and UEFA Women's Champions League as available competitions?

And while personally I would appreciate reports on some other competitions like the FA Cup, League Cup, and the Canadian Football League, I suspect getting those set up and reported is a different dynamic overall.

**Comment by sereneblue** [comment]
Hi @MLKahnt,

I've updated the teams and added the following leagues: UEFA Europa League, UEFA Europa Conference League, UEFA Women's Champions League, FA Cup, and Leagues Cup.

**Comment by MLKahnt** [comment]
Hi SereneBlue,Thanks - looks excellent!I just noticed, however, that for the NHL teams, the Seattle Kraken are missing. If someone selects all of the other exams, their games will show, but if someone is only interested in them, well…Mark L Kahnt On Sep 6, 2023, at 8:17 PM, sereneblue ***@***.***> wrote:﻿
Hi @MLKahnt,
I've updated the teams and added the following leagues: UEFA Europa League, UEFA Europa Conference League, UEFA Women's Champions League, FA Cup, and Leagues Cup.

**Comment by sereneblue** [comment]
Thanks for catching that @MLKahnt. I've released an update that addresses this issue.
