### ISSUE TITLE
Some settings are only reflected on next update

### ISSUE THREAD

**Issue by terminalmage** [sereneblue/gnome-shell-extension-colosseum#15]
Changes to a couple of the config settings (`compact-mode` and `followed-only`) do not take effect until the next update interval. With the default update interval being 5 minutes, this means that you can switch these options and not see the changes for up to 5 minutes. This is confusing when compared with `position-in-topbar`, for which changes take effect immediately.

Is this a limitation of gnome-shell? I'm still new to gnome-shell (until a few weeks ago I hadn't used GNOME since before GNOME 3), but do extensions not have a way of detecting gsettings changes as they happen?

**Comment by sereneblue** [comment]
Hi @terminalmage,

No, this isn't a limitation of gnome-shell. I'll review and update this for the next version.

**Comment by terminalmage** [comment]
From a surface-level look at the code, this appears to be because the contents of the GridLayout are torn down and replaced every time the interval expires. It ends up getting the new configuration when it rebuilds the grid.

**Comment by sereneblue** [comment]
This is resolved in the next update.
