### ISSUE TITLE
IDEA: Click events to launch GameCast URLs in default browser

### ISSUE THREAD

**Issue by terminalmage** [sereneblue/gnome-shell-extension-colosseum#16]
The API the code is using to pull data includes GameCast URLs for each game. It would be really neat if you could click (or perhaps double-click to avoid inadvertent triggering) a game to launch the GameCast URL for that game.

From what I can grok of the code this might be a significant redesign of how the scores are displayed. I did some reading about GridLayout and I don't see a way to associate individual rows of the grid with click events.

I'm a novice when it comes to gnome-shell extension development, but I'm a perfectly capable developer and am happy to look into this on my own and see what I can come up with, if you point me in the right direction.

**Comment by sereneblue** [comment]
Hi @terminalmage,

Cool idea! The space under the score could be used for this. If it's as simple as adding a link, I'll try to have this included in the next update.

**Comment by terminalmage** [comment]
I like the idea of making the clickable item a subset of the row, so that clicking it is a more intentional action. It would reduce the likelihood that you trigger it accidentally by tapping a laptop touchpad, for example.

I'd be interested in seeing how this gets implemented. I'm trying to teach myself gnome-shell extension development by participating in / following the development of a couple extensions.

**Comment by sereneblue** [comment]
@terminalmage This has been added in the next update.
