### ISSUE TITLE
Support for Israeli Premier League

### ISSUE THREAD

**Issue by Latnook** [sereneblue/gnome-shell-extension-colosseum#19]
Hello,
I was wondering: what is the chance of the Israeli Premier League added to the extension?
It would be awesome if it's possible and would be implemented.
Thank you.

**Comment by sereneblue** [comment]
Hi @Latnook,

Fortunately, it seems the ESPN API does support this league so it shouldn't take too long to add. I'll release an update soon.

**Comment by sereneblue** [comment]
@Latnook This has been added in the latest update. It will be available on the GNOME site once approved.

**Comment by Latnook** [comment]
Awesome. Just received the update. Thank you very much!!
