### ISSUE TITLE
text/icon gone when game starts

### ISSUE THREAD

**Issue by jorp** [sereneblue/gnome-shell-extension-colosseum#3]
Since upgrading to version 4 the icon and text has disappeared when a followed game begins. The region where it would normally display however is still clickable/usable.

![Screenshot from 2021-07-23 19-39-58](https://user-images.githubusercontent.com/18096435/126850514-0b537a46-ff37-4e7a-85ea-22617e561d6f.png)

**Comment by sereneblue** [comment]
Hi @jorp, 

Thanks for pointing out this issue. It'll be resolved in the next update.
