### ISSUE TITLE
English Premier League

### ISSUE THREAD

**Issue by catbabylon** [sereneblue/gnome-shell-extension-colosseum#5]
Looking at the teams, I don't think this got updated for the 2021/22 season. Please can you remove Fulham, West Bromwich Albion and Sheffield United and add Norwich City, Watford and Brentford.

Incidentally how does the extension update for relegation and promotion? I'm guessing manually? If so, should I raise another issue with the league changes for the 2022/23 season?

**Comment by sereneblue** [comment]
Hi @catbabylon, thanks for reporting this issue. I'm not too familiar with how the EPL works. I assumed the teams were static. I'll correct this in an update. 

Yes, the team list is set manually. Please do raise another issue for the league changes for 2022/23. Thanks again.
