### ISSUE TITLE
Add Fifa World cup 2022

### ISSUE THREAD

**Issue by hasrack** [sereneblue/gnome-shell-extension-colosseum#7]
It would be really nice if you could add the Fifa World cup 2022 in tournament section.

Here are the participants of the upcoming World cup
![FIFA-World-Cup-Qatar-2022-Final-groups](https://user-images.githubusercontent.com/9502473/187058823-d48713a2-5db5-4f21-a805-9bd79f565665.jpg)

Thanks a lot for this extension.

**Comment by sereneblue** [comment]
Hi @hasrack,

Sure, thanks for the heads up! I'll release an update soon.

**Comment by hasrack** [comment]
Thanks a lot.
