### ISSUE TITLE
Extension doesn't appear on top bar anymore

### ISSUE THREAD

**Issue by catbabylon** [sereneblue/gnome-shell-extension-colosseum#9]
I've been away from GNOME for a while but am back on it using GNOME 44 in Tumbleweed. I've installed Colosseum, but it doesn't appear at the top regardless of the settings I choose and what teams/sports I follow. I've tried disabling and enabling the AppindicatorKstatusnotifier which doesn't have any effect.

**Comment by sereneblue** [comment]
Hi @catbabylon,

There are a couple of reasons why the extension might not appear in the top bar:

1. There aren't any games for any of the enabled leagues.
2. There was an error with the request so it couldn't parse any information to add to the top bar.

You can check if you're encountering #1 by enabling a couple of leagues that have games today and toggling the extension.

For #2, you can monitor the output from gnome-shell `journalctl -f | grep gnome-shell` and see if there's anything relevant there when you toggle the extension. 

Hope this helps.

**Comment by catbabylon** [comment]
Sorry this fell out of my head. I just tested this by adding MLB and after restarting the addon the icon does appear and there is a list of results showing in the drop-down.

Will have to wait for the new EPL to start and see if it works when only following a team in that league.

**Comment by sereneblue** [comment]
Glad to hear it works for you. I've done some testing with the EPL using future dates and it seems to work fine. I'll close this issue, but feel free to let me know if you're still experiencing issues.
